[package]
name = "aoc2020"
version = "0.1.0"
authors = ["jpbougie <jean-philippe@demarque.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.0"
regex = "1.4.2"
